// ignore_for_file: constant_identifier_names

enum TransactionType { CASH_IN, CASH_OUT }

enum TransactionCategory {
  SALE_PAYMENT,
  PURCHASE_PAYMENT,
  EXPENSE_RENT,
  EXPENSE_SALARY,
  EXPENSE_UTILITIES,
  OWNER_DRAWING,
  CAPITAL_INJECTION,
  OTHER_INCOME,
  OTHER_EXPENSE,
  SALE_RETURN,
  PURCHASE_RETURN,
}

enum PaymentMethod { CASH, BANK_TRANSFER, CARD, CHEQUE, CREDIT }
